name: code_test_flutter
description: This is the boilerplate template repository for flutter projects. This showcases common use cases and a base architecture.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Flutter Configuration
# • Flutter version 3.19.6
# • Dart version 3.3.4

version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^16.0.0
  rxdart: ^0.28.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  drift: ^2.28.0
  drift_flutter: ^0.2.4
  shared_preferences: ^2.2.3
  flutter_bloc: ^9.1.1
  sprintf: ^7.0.0
  intl: ^0.20.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  logger: ^2.3.0
  html: ^0.15.4
  injectable: ^2.5.0
  freezed_annotation: ^3.1.0
  collection: ^1.18.0
  fast_immutable_collections: ^11.0.4
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  crypto: ^3.0.3
  path: ^1.9.0
  fluttertoast: ^8.2.12
  async: ^2.11.0
  path_provider: ^2.1.5

dev_dependencies:
  test: ^1.24.9
  analyzer: ^7.7.1
  build_runner: ^2.4.9
  drift_dev: ^2.28.0
  freezed: ^3.1.0
  injectable_generator: ^2.7.0
  retrofit_generator: ^9.7.0
  dynamic_config_generator: ^0.5.0
  flutter_launcher_icons: ^0.14.4
  bloc_test: ^10.0.0
  mockito: ^5.4.6
  flutter_lints: ^6.0.0
  flutter_gen_runner: ^5.4.0

flutter_icons:
  # image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/launcher/common_launcher.png"
  image_path_ios: "assets/launcher/common_launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/launcher/android_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/launcher/android_foreground.png" # only available for Android 8.0 devices and above

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/cabin-regular.ttf
        - asset: assets/fonts/cabin-bold.ttf
          weight: 700
flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml